# Generated by Django 5.2.13 on 2026-08-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_events_2_n8n', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfig',
            name='event',
            field=models.CharField(choices=[('org.openedx.learning.student.registration.completed.v1', 'Student registration completed'), ('org.openedx.learning.course.enrollment.created.v1', 'Student enrollment created'), ('org.openedx.learning.course.persistent_grade_summary.changed.v1', 'Persistent grade summary changed')], db_index=True, help_text='The openedx-events event_type this webhook applies to, e.g.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
