# Generated by Django 5.2.13 on 2026-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_events_2_n8n', '0002_alter_webhookconfig_event_alter_webhookconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfig',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('header', 'Header Auth'), ('jwt', 'JWT Auth')], default='none', help_text="Matches the credential type configured on the n8n Webhook node.", max_length=10),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='basic_auth_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='basic_auth_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='header_auth_name',
            field=models.CharField(blank=True, help_text='e.g. Authorization', max_length=255),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='header_auth_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='jwt_auth_secret',
            field=models.CharField(blank=True, help_text="Passphrase configured on n8n's JWT Auth credential (HS256).", max_length=255),
        ),
    ]
