# Generated by Django 5.2.13 on 2026-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_events_2_n8n', '0004_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, help_text='event_metadata.id, used to deduplicate re-sent events.', max_length=36),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_success', True)), fields=('event_id',), name='unique_successful_event_id'),
        ),
    ]
